name: daraz
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1

  image: ^4.0.13
  cached_network_image: ^3.2.3
  video_player: ^2.5.1
  google_nav_bar: ^5.0.6

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - images/